Update Fatih Kalifa's profile
mazipan/awesome-js-dev-id pull request #17
Opened 2019-06-24 06:45 UTC by asendia

This commit sole purpose is to appreciate technical excellence of Fatih Kalifa.

2019-06-24 10:27 UTC, fawwaz approved these changes
~LGTM~ Commented

2019-06-24 10:38 UTC, masbagal approved these changes
LGTM

2019-06-24 10:40 UTC, fawwaz requested changes
Please add ReasonML.

2019-06-24 10:40 UTC, fawwaz commented on README.md
> +  - Skills: #React, #NodeJs, #Svelte, #Rust, #GraphQL
#ReasonML

2019-06-24 11:56 UTC, asendia commented on README.md
> +  - Skills: #React, #NodeJs, #Svelte, #Rust, #GraphQL
Added

2019-06-25 00:45 UTC, fawwaz approved these changes

2019-06-25 02:47 UTC, merged